//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ViewModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SearchEntities : DbContext
    {
        public SearchEntities()
            : base("name=SearchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_booking_users> tbl_booking_users { get; set; }
        public virtual DbSet<tbl_collaborative> tbl_collaborative { get; set; }
        public virtual DbSet<tbl_dining_halls> tbl_dining_halls { get; set; }
        public virtual DbSet<tbl_event_manager> tbl_event_manager { get; set; }
        public virtual DbSet<tbl_faculty_IIT> tbl_faculty_IIT { get; set; }
        public virtual DbSet<tbl_halls> tbl_halls { get; set; }
        public virtual DbSet<tbl_mst_approval_status> tbl_mst_approval_status { get; set; }
        public virtual DbSet<tbl_mst_dept_ICSR> tbl_mst_dept_ICSR { get; set; }
        public virtual DbSet<tbl_mst_dept_IIT> tbl_mst_dept_IIT { get; set; }
        public virtual DbSet<tbl_mst_designation_IIT> tbl_mst_designation_IIT { get; set; }
        public virtual DbSet<tbl_mst_hallStatus> tbl_mst_hallStatus { get; set; }
        public virtual DbSet<tbl_mst_mode_of_payment> tbl_mst_mode_of_payment { get; set; }
        public virtual DbSet<tbl_mst_reservation_type> tbl_mst_reservation_type { get; set; }
        public virtual DbSet<tbl_payment> tbl_payment { get; set; }
        public virtual DbSet<tbl_receipt> tbl_receipt { get; set; }
        public virtual DbSet<tbl_trx_email_log> tbl_trx_email_log { get; set; }
        public virtual DbSet<tbl_trx_reservation> tbl_trx_reservation { get; set; }
        public virtual DbSet<tbl_users_ICSR> tbl_users_ICSR { get; set; }
    
        public virtual int sp_add_booking_user(string name, Nullable<long> deptId, string mobile_no, string tele_no, string emailId)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var deptIdParameter = deptId.HasValue ?
                new ObjectParameter("deptId", deptId) :
                new ObjectParameter("deptId", typeof(long));
    
            var mobile_noParameter = mobile_no != null ?
                new ObjectParameter("mobile_no", mobile_no) :
                new ObjectParameter("mobile_no", typeof(string));
    
            var tele_noParameter = tele_no != null ?
                new ObjectParameter("tele_no", tele_no) :
                new ObjectParameter("tele_no", typeof(string));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("emailId", emailId) :
                new ObjectParameter("emailId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_add_booking_user", nameParameter, deptIdParameter, mobile_noParameter, tele_noParameter, emailIdParameter);
        }
    
        public virtual ObjectResult<sp_add_reservation_Result> sp_add_reservation(Nullable<int> hallId, Nullable<int> res_typeId, Nullable<System.DateTime> start_date, Nullable<System.DateTime> end_date, Nullable<System.TimeSpan> start_time, Nullable<System.TimeSpan> end_time, string programme_title, Nullable<bool> is_collaborative, string facultyName, Nullable<long> deptId, string tele_no, string mobile_no, string emailId, string event_manager_name, string em_mobile_no, string em_emailId, string collaborative_faculty, Nullable<long> cfac_deptId, string cfac_tele_no, string cfac_mobile_no, string cfac_emailId)
        {
            var hallIdParameter = hallId.HasValue ?
                new ObjectParameter("hallId", hallId) :
                new ObjectParameter("hallId", typeof(int));
    
            var res_typeIdParameter = res_typeId.HasValue ?
                new ObjectParameter("res_typeId", res_typeId) :
                new ObjectParameter("res_typeId", typeof(int));
    
            var start_dateParameter = start_date.HasValue ?
                new ObjectParameter("start_date", start_date) :
                new ObjectParameter("start_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            var start_timeParameter = start_time.HasValue ?
                new ObjectParameter("start_time", start_time) :
                new ObjectParameter("start_time", typeof(System.TimeSpan));
    
            var end_timeParameter = end_time.HasValue ?
                new ObjectParameter("end_time", end_time) :
                new ObjectParameter("end_time", typeof(System.TimeSpan));
    
            var programme_titleParameter = programme_title != null ?
                new ObjectParameter("programme_title", programme_title) :
                new ObjectParameter("programme_title", typeof(string));
    
            var is_collaborativeParameter = is_collaborative.HasValue ?
                new ObjectParameter("is_collaborative", is_collaborative) :
                new ObjectParameter("is_collaborative", typeof(bool));
    
            var facultyNameParameter = facultyName != null ?
                new ObjectParameter("facultyName", facultyName) :
                new ObjectParameter("facultyName", typeof(string));
    
            var deptIdParameter = deptId.HasValue ?
                new ObjectParameter("deptId", deptId) :
                new ObjectParameter("deptId", typeof(long));
    
            var tele_noParameter = tele_no != null ?
                new ObjectParameter("tele_no", tele_no) :
                new ObjectParameter("tele_no", typeof(string));
    
            var mobile_noParameter = mobile_no != null ?
                new ObjectParameter("mobile_no", mobile_no) :
                new ObjectParameter("mobile_no", typeof(string));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("emailId", emailId) :
                new ObjectParameter("emailId", typeof(string));
    
            var event_manager_nameParameter = event_manager_name != null ?
                new ObjectParameter("event_manager_name", event_manager_name) :
                new ObjectParameter("event_manager_name", typeof(string));
    
            var em_mobile_noParameter = em_mobile_no != null ?
                new ObjectParameter("em_mobile_no", em_mobile_no) :
                new ObjectParameter("em_mobile_no", typeof(string));
    
            var em_emailIdParameter = em_emailId != null ?
                new ObjectParameter("em_emailId", em_emailId) :
                new ObjectParameter("em_emailId", typeof(string));
    
            var collaborative_facultyParameter = collaborative_faculty != null ?
                new ObjectParameter("collaborative_faculty", collaborative_faculty) :
                new ObjectParameter("collaborative_faculty", typeof(string));
    
            var cfac_deptIdParameter = cfac_deptId.HasValue ?
                new ObjectParameter("cfac_deptId", cfac_deptId) :
                new ObjectParameter("cfac_deptId", typeof(long));
    
            var cfac_tele_noParameter = cfac_tele_no != null ?
                new ObjectParameter("cfac_tele_no", cfac_tele_no) :
                new ObjectParameter("cfac_tele_no", typeof(string));
    
            var cfac_mobile_noParameter = cfac_mobile_no != null ?
                new ObjectParameter("cfac_mobile_no", cfac_mobile_no) :
                new ObjectParameter("cfac_mobile_no", typeof(string));
    
            var cfac_emailIdParameter = cfac_emailId != null ?
                new ObjectParameter("cfac_emailId", cfac_emailId) :
                new ObjectParameter("cfac_emailId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_add_reservation_Result>("sp_add_reservation", hallIdParameter, res_typeIdParameter, start_dateParameter, end_dateParameter, start_timeParameter, end_timeParameter, programme_titleParameter, is_collaborativeParameter, facultyNameParameter, deptIdParameter, tele_noParameter, mobile_noParameter, emailIdParameter, event_manager_nameParameter, em_mobile_noParameter, em_emailIdParameter, collaborative_facultyParameter, cfac_deptIdParameter, cfac_tele_noParameter, cfac_mobile_noParameter, cfac_emailIdParameter);
        }
    
        public virtual ObjectResult<sp_booking_list_Result> sp_booking_list()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_booking_list_Result>("sp_booking_list");
        }
    
        public virtual ObjectResult<sp_check_availability_Result> sp_check_availability(Nullable<int> hallId, Nullable<System.DateTime> start_date, Nullable<System.TimeSpan> start_time, Nullable<System.DateTime> end_date, Nullable<System.TimeSpan> end_time)
        {
            var hallIdParameter = hallId.HasValue ?
                new ObjectParameter("hallId", hallId) :
                new ObjectParameter("hallId", typeof(int));
    
            var start_dateParameter = start_date.HasValue ?
                new ObjectParameter("start_date", start_date) :
                new ObjectParameter("start_date", typeof(System.DateTime));
    
            var start_timeParameter = start_time.HasValue ?
                new ObjectParameter("start_time", start_time) :
                new ObjectParameter("start_time", typeof(System.TimeSpan));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            var end_timeParameter = end_time.HasValue ?
                new ObjectParameter("end_time", end_time) :
                new ObjectParameter("end_time", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_check_availability_Result>("sp_check_availability", hallIdParameter, start_dateParameter, start_timeParameter, end_dateParameter, end_timeParameter);
        }
    
        public virtual int sp_email_log(Nullable<long> reservationId, string from_mailId, string to_mailId, string cc1_mailId, string cc2_mailId, string cc3_mailId, string mail_subject, string mail_body, string attachment_file_name, Nullable<bool> is_reminder)
        {
            var reservationIdParameter = reservationId.HasValue ?
                new ObjectParameter("reservationId", reservationId) :
                new ObjectParameter("reservationId", typeof(long));
    
            var from_mailIdParameter = from_mailId != null ?
                new ObjectParameter("from_mailId", from_mailId) :
                new ObjectParameter("from_mailId", typeof(string));
    
            var to_mailIdParameter = to_mailId != null ?
                new ObjectParameter("to_mailId", to_mailId) :
                new ObjectParameter("to_mailId", typeof(string));
    
            var cc1_mailIdParameter = cc1_mailId != null ?
                new ObjectParameter("cc1_mailId", cc1_mailId) :
                new ObjectParameter("cc1_mailId", typeof(string));
    
            var cc2_mailIdParameter = cc2_mailId != null ?
                new ObjectParameter("cc2_mailId", cc2_mailId) :
                new ObjectParameter("cc2_mailId", typeof(string));
    
            var cc3_mailIdParameter = cc3_mailId != null ?
                new ObjectParameter("cc3_mailId", cc3_mailId) :
                new ObjectParameter("cc3_mailId", typeof(string));
    
            var mail_subjectParameter = mail_subject != null ?
                new ObjectParameter("mail_subject", mail_subject) :
                new ObjectParameter("mail_subject", typeof(string));
    
            var mail_bodyParameter = mail_body != null ?
                new ObjectParameter("mail_body", mail_body) :
                new ObjectParameter("mail_body", typeof(string));
    
            var attachment_file_nameParameter = attachment_file_name != null ?
                new ObjectParameter("attachment_file_name", attachment_file_name) :
                new ObjectParameter("attachment_file_name", typeof(string));
    
            var is_reminderParameter = is_reminder.HasValue ?
                new ObjectParameter("is_reminder", is_reminder) :
                new ObjectParameter("is_reminder", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_email_log", reservationIdParameter, from_mailIdParameter, to_mailIdParameter, cc1_mailIdParameter, cc2_mailIdParameter, cc3_mailIdParameter, mail_subjectParameter, mail_bodyParameter, attachment_file_nameParameter, is_reminderParameter);
        }
    
        public virtual ObjectResult<spGet_faculty_departments_Result> spGet_faculty_departments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_faculty_departments_Result>("spGet_faculty_departments");
        }
    
        public virtual ObjectResult<spGet_Halls_Result> spGet_Halls()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_Halls_Result>("spGet_Halls");
        }
    }
}
