//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trx_reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_trx_reservation()
        {
            this.tbl_collaborative = new HashSet<tbl_collaborative>();
            this.tbl_event_manager = new HashSet<tbl_event_manager>();
            this.tbl_faculty_IIT = new HashSet<tbl_faculty_IIT>();
            this.tbl_payment = new HashSet<tbl_payment>();
            this.tbl_trx_email_log = new HashSet<tbl_trx_email_log>();
        }
    
        public long reservationId { get; set; }
        public int hallId { get; set; }
        public Nullable<int> d_hallId { get; set; }
        public int res_typeId { get; set; }
        public string programme_title { get; set; }
        public Nullable<bool> is_collaborative { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public Nullable<bool> is_with_dining { get; set; }
        public int approval_statusId { get; set; }
        public Nullable<long> approvedBy { get; set; }
        public Nullable<System.DateTime> ApprovedTime { get; set; }
        public Nullable<decimal> reservation_amount { get; set; }
        public Nullable<bool> is_paid { get; set; }
        public Nullable<System.DateTime> createdTime { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
        public bool is_fullDay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_collaborative> tbl_collaborative { get; set; }
        public virtual tbl_dining_halls tbl_dining_halls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_event_manager> tbl_event_manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_faculty_IIT> tbl_faculty_IIT { get; set; }
        public virtual tbl_halls tbl_halls { get; set; }
        public virtual tbl_mst_approval_status tbl_mst_approval_status { get; set; }
        public virtual tbl_mst_reservation_type tbl_mst_reservation_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_payment> tbl_payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_trx_email_log> tbl_trx_email_log { get; set; }
        public virtual tbl_users_ICSR tbl_users_ICSR { get; set; }
        public virtual tbl_trx_reservation tbl_trx_reservation1 { get; set; }
        public virtual tbl_trx_reservation tbl_trx_reservation2 { get; set; }
    }
}
