//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_event_manager
    {
        public long event_managerId { get; set; }
        public long reservationId { get; set; }
        public string event_manager_name { get; set; }
        public string emailId { get; set; }
        public string mobile_no { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
    
        public virtual tbl_trx_reservation tbl_trx_reservation { get; set; }
    }
}
