//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_users_ICSR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_users_ICSR()
        {
            this.tbl_trx_reservation = new HashSet<tbl_trx_reservation>();
        }
    
        public long userId { get; set; }
        public string full_name { get; set; }
        public string designation { get; set; }
        public int deptId { get; set; }
        public string userName { get; set; }
        public string passWord { get; set; }
        public Nullable<bool> is_approver { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<System.DateTime> createdtime { get; set; }
    
        public virtual tbl_mst_dept_ICSR tbl_mst_dept_ICSR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_trx_reservation> tbl_trx_reservation { get; set; }
    }
}
